//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.DataManager {
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Film", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Film : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Film_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Film_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Film_PicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExplanField;
        
        private System.DateTime Vision_DateField;
        
        private decimal ImdbField;
        
        private int TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Film_ID {
            get {
                return this.Film_IDField;
            }
            set {
                if ((this.Film_IDField.Equals(value) != true)) {
                    this.Film_IDField = value;
                    this.RaisePropertyChanged("Film_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Film_Name {
            get {
                return this.Film_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Film_NameField, value) != true)) {
                    this.Film_NameField = value;
                    this.RaisePropertyChanged("Film_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Film_Pic {
            get {
                return this.Film_PicField;
            }
            set {
                if ((object.ReferenceEquals(this.Film_PicField, value) != true)) {
                    this.Film_PicField = value;
                    this.RaisePropertyChanged("Film_Pic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Explan {
            get {
                return this.ExplanField;
            }
            set {
                if ((object.ReferenceEquals(this.ExplanField, value) != true)) {
                    this.ExplanField = value;
                    this.RaisePropertyChanged("Explan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime Vision_Date {
            get {
                return this.Vision_DateField;
            }
            set {
                if ((this.Vision_DateField.Equals(value) != true)) {
                    this.Vision_DateField = value;
                    this.RaisePropertyChanged("Vision_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal Imdb {
            get {
                return this.ImdbField;
            }
            set {
                if ((this.ImdbField.Equals(value) != true)) {
                    this.ImdbField = value;
                    this.RaisePropertyChanged("Imdb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataManager.DataManagerSoap")]
    public interface DataManagerSoap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        WebApp.DataManager.LoginResponse Login(WebApp.DataManager.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApp.DataManager.LoginResponse> LoginAsync(WebApp.DataManager.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name Film_Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilmEkle", ReplyAction="*")]
        WebApp.DataManager.FilmEkleResponse FilmEkle(WebApp.DataManager.FilmEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilmEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApp.DataManager.FilmEkleResponse> FilmEkleAsync(WebApp.DataManager.FilmEkleRequest request);
        
        // CODEGEN: Generating message contract since element name Film_Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilmGuncelle", ReplyAction="*")]
        WebApp.DataManager.FilmGuncelleResponse FilmGuncelle(WebApp.DataManager.FilmGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilmGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApp.DataManager.FilmGuncelleResponse> FilmGuncelleAsync(WebApp.DataManager.FilmGuncelleRequest request);
        
        // CODEGEN: Generating message contract since element name FilmDetayGetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilmDetayGetir", ReplyAction="*")]
        WebApp.DataManager.FilmDetayGetirResponse FilmDetayGetir(WebApp.DataManager.FilmDetayGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilmDetayGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApp.DataManager.FilmDetayGetirResponse> FilmDetayGetirAsync(WebApp.DataManager.FilmDetayGetirRequest request);
        
        // CODEGEN: Generating message contract since element name FilmListeleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilmListele", ReplyAction="*")]
        WebApp.DataManager.FilmListeleResponse FilmListele(WebApp.DataManager.FilmListeleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilmListele", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApp.DataManager.FilmListeleResponse> FilmListeleAsync(WebApp.DataManager.FilmListeleRequest request);
        
        // CODEGEN: Generating message contract since element name FilmSilResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilmSil", ReplyAction="*")]
        WebApp.DataManager.FilmSilResponse FilmSil(WebApp.DataManager.FilmSilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilmSil", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApp.DataManager.FilmSilResponse> FilmSilAsync(WebApp.DataManager.FilmSilRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public WebApp.DataManager.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(WebApp.DataManager.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string UserName, string Password) {
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApp.DataManager.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(WebApp.DataManager.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilmEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilmEkle", Namespace="http://tempuri.org/", Order=0)]
        public WebApp.DataManager.FilmEkleRequestBody Body;
        
        public FilmEkleRequest() {
        }
        
        public FilmEkleRequest(WebApp.DataManager.FilmEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilmEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Film_Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Explan;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime Vision_Date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Imdb;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Time;
        
        public FilmEkleRequestBody() {
        }
        
        public FilmEkleRequestBody(string Film_Name, string Explan, System.DateTime Vision_Date, int Imdb, int Time) {
            this.Film_Name = Film_Name;
            this.Explan = Explan;
            this.Vision_Date = Vision_Date;
            this.Imdb = Imdb;
            this.Time = Time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilmEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilmEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApp.DataManager.FilmEkleResponseBody Body;
        
        public FilmEkleResponse() {
        }
        
        public FilmEkleResponse(WebApp.DataManager.FilmEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilmEkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FilmEkleResult;
        
        public FilmEkleResponseBody() {
        }
        
        public FilmEkleResponseBody(string FilmEkleResult) {
            this.FilmEkleResult = FilmEkleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilmGuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilmGuncelle", Namespace="http://tempuri.org/", Order=0)]
        public WebApp.DataManager.FilmGuncelleRequestBody Body;
        
        public FilmGuncelleRequest() {
        }
        
        public FilmGuncelleRequest(WebApp.DataManager.FilmGuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilmGuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Film_Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Film_Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Explan;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime Vision_Date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Imdb;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Time;
        
        public FilmGuncelleRequestBody() {
        }
        
        public FilmGuncelleRequestBody(int Film_Id, string Film_Name, string Explan, System.DateTime Vision_Date, int Imdb, int Time) {
            this.Film_Id = Film_Id;
            this.Film_Name = Film_Name;
            this.Explan = Explan;
            this.Vision_Date = Vision_Date;
            this.Imdb = Imdb;
            this.Time = Time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilmGuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilmGuncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApp.DataManager.FilmGuncelleResponseBody Body;
        
        public FilmGuncelleResponse() {
        }
        
        public FilmGuncelleResponse(WebApp.DataManager.FilmGuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilmGuncelleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FilmGuncelleResult;
        
        public FilmGuncelleResponseBody() {
        }
        
        public FilmGuncelleResponseBody(string FilmGuncelleResult) {
            this.FilmGuncelleResult = FilmGuncelleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilmDetayGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilmDetayGetir", Namespace="http://tempuri.org/", Order=0)]
        public WebApp.DataManager.FilmDetayGetirRequestBody Body;
        
        public FilmDetayGetirRequest() {
        }
        
        public FilmDetayGetirRequest(WebApp.DataManager.FilmDetayGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilmDetayGetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int filmID;
        
        public FilmDetayGetirRequestBody() {
        }
        
        public FilmDetayGetirRequestBody(int filmID) {
            this.filmID = filmID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilmDetayGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilmDetayGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApp.DataManager.FilmDetayGetirResponseBody Body;
        
        public FilmDetayGetirResponse() {
        }
        
        public FilmDetayGetirResponse(WebApp.DataManager.FilmDetayGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilmDetayGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApp.DataManager.Film FilmDetayGetirResult;
        
        public FilmDetayGetirResponseBody() {
        }
        
        public FilmDetayGetirResponseBody(WebApp.DataManager.Film FilmDetayGetirResult) {
            this.FilmDetayGetirResult = FilmDetayGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilmListeleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilmListele", Namespace="http://tempuri.org/", Order=0)]
        public WebApp.DataManager.FilmListeleRequestBody Body;
        
        public FilmListeleRequest() {
        }
        
        public FilmListeleRequest(WebApp.DataManager.FilmListeleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FilmListeleRequestBody {
        
        public FilmListeleRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilmListeleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilmListeleResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApp.DataManager.FilmListeleResponseBody Body;
        
        public FilmListeleResponse() {
        }
        
        public FilmListeleResponse(WebApp.DataManager.FilmListeleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilmListeleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public List<WebApp.DataManager.Film> FilmListeleResult;
        
        public FilmListeleResponseBody() {
        }
        
        public FilmListeleResponseBody(List<WebApp.DataManager.Film> FilmListeleResult) {
            this.FilmListeleResult = FilmListeleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilmSilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilmSil", Namespace="http://tempuri.org/", Order=0)]
        public WebApp.DataManager.FilmSilRequestBody Body;
        
        public FilmSilRequest() {
        }
        
        public FilmSilRequest(WebApp.DataManager.FilmSilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilmSilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Film_Id;
        
        public FilmSilRequestBody() {
        }
        
        public FilmSilRequestBody(int Film_Id) {
            this.Film_Id = Film_Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilmSilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilmSilResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApp.DataManager.FilmSilResponseBody Body;
        
        public FilmSilResponse() {
        }
        
        public FilmSilResponse(WebApp.DataManager.FilmSilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilmSilResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FilmSilResult;
        
        public FilmSilResponseBody() {
        }
        
        public FilmSilResponseBody(string FilmSilResult) {
            this.FilmSilResult = FilmSilResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataManagerSoapChannel : WebApp.DataManager.DataManagerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataManagerSoapClient : System.ServiceModel.ClientBase<WebApp.DataManager.DataManagerSoap>, WebApp.DataManager.DataManagerSoap {
        
        public DataManagerSoapClient() {
        }
        
        public DataManagerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataManagerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataManagerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataManagerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.DataManager.LoginResponse WebApp.DataManager.DataManagerSoap.Login(WebApp.DataManager.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string UserName, string Password) {
            WebApp.DataManager.LoginRequest inValue = new WebApp.DataManager.LoginRequest();
            inValue.Body = new WebApp.DataManager.LoginRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            WebApp.DataManager.LoginResponse retVal = ((WebApp.DataManager.DataManagerSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApp.DataManager.LoginResponse> WebApp.DataManager.DataManagerSoap.LoginAsync(WebApp.DataManager.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApp.DataManager.LoginResponse> LoginAsync(string UserName, string Password) {
            WebApp.DataManager.LoginRequest inValue = new WebApp.DataManager.LoginRequest();
            inValue.Body = new WebApp.DataManager.LoginRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            return ((WebApp.DataManager.DataManagerSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.DataManager.FilmEkleResponse WebApp.DataManager.DataManagerSoap.FilmEkle(WebApp.DataManager.FilmEkleRequest request) {
            return base.Channel.FilmEkle(request);
        }
        
        public string FilmEkle(string Film_Name, string Explan, System.DateTime Vision_Date, int Imdb, int Time) {
            WebApp.DataManager.FilmEkleRequest inValue = new WebApp.DataManager.FilmEkleRequest();
            inValue.Body = new WebApp.DataManager.FilmEkleRequestBody();
            inValue.Body.Film_Name = Film_Name;
            inValue.Body.Explan = Explan;
            inValue.Body.Vision_Date = Vision_Date;
            inValue.Body.Imdb = Imdb;
            inValue.Body.Time = Time;
            WebApp.DataManager.FilmEkleResponse retVal = ((WebApp.DataManager.DataManagerSoap)(this)).FilmEkle(inValue);
            return retVal.Body.FilmEkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApp.DataManager.FilmEkleResponse> WebApp.DataManager.DataManagerSoap.FilmEkleAsync(WebApp.DataManager.FilmEkleRequest request) {
            return base.Channel.FilmEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApp.DataManager.FilmEkleResponse> FilmEkleAsync(string Film_Name, string Explan, System.DateTime Vision_Date, int Imdb, int Time) {
            WebApp.DataManager.FilmEkleRequest inValue = new WebApp.DataManager.FilmEkleRequest();
            inValue.Body = new WebApp.DataManager.FilmEkleRequestBody();
            inValue.Body.Film_Name = Film_Name;
            inValue.Body.Explan = Explan;
            inValue.Body.Vision_Date = Vision_Date;
            inValue.Body.Imdb = Imdb;
            inValue.Body.Time = Time;
            return ((WebApp.DataManager.DataManagerSoap)(this)).FilmEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.DataManager.FilmGuncelleResponse WebApp.DataManager.DataManagerSoap.FilmGuncelle(WebApp.DataManager.FilmGuncelleRequest request) {
            return base.Channel.FilmGuncelle(request);
        }
        
        public string FilmGuncelle(int Film_Id, string Film_Name, string Explan, System.DateTime Vision_Date, int Imdb, int Time) {
            WebApp.DataManager.FilmGuncelleRequest inValue = new WebApp.DataManager.FilmGuncelleRequest();
            inValue.Body = new WebApp.DataManager.FilmGuncelleRequestBody();
            inValue.Body.Film_Id = Film_Id;
            inValue.Body.Film_Name = Film_Name;
            inValue.Body.Explan = Explan;
            inValue.Body.Vision_Date = Vision_Date;
            inValue.Body.Imdb = Imdb;
            inValue.Body.Time = Time;
            WebApp.DataManager.FilmGuncelleResponse retVal = ((WebApp.DataManager.DataManagerSoap)(this)).FilmGuncelle(inValue);
            return retVal.Body.FilmGuncelleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApp.DataManager.FilmGuncelleResponse> WebApp.DataManager.DataManagerSoap.FilmGuncelleAsync(WebApp.DataManager.FilmGuncelleRequest request) {
            return base.Channel.FilmGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApp.DataManager.FilmGuncelleResponse> FilmGuncelleAsync(int Film_Id, string Film_Name, string Explan, System.DateTime Vision_Date, int Imdb, int Time) {
            WebApp.DataManager.FilmGuncelleRequest inValue = new WebApp.DataManager.FilmGuncelleRequest();
            inValue.Body = new WebApp.DataManager.FilmGuncelleRequestBody();
            inValue.Body.Film_Id = Film_Id;
            inValue.Body.Film_Name = Film_Name;
            inValue.Body.Explan = Explan;
            inValue.Body.Vision_Date = Vision_Date;
            inValue.Body.Imdb = Imdb;
            inValue.Body.Time = Time;
            return ((WebApp.DataManager.DataManagerSoap)(this)).FilmGuncelleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.DataManager.FilmDetayGetirResponse WebApp.DataManager.DataManagerSoap.FilmDetayGetir(WebApp.DataManager.FilmDetayGetirRequest request) {
            return base.Channel.FilmDetayGetir(request);
        }
        
        public WebApp.DataManager.Film FilmDetayGetir(int filmID) {
            WebApp.DataManager.FilmDetayGetirRequest inValue = new WebApp.DataManager.FilmDetayGetirRequest();
            inValue.Body = new WebApp.DataManager.FilmDetayGetirRequestBody();
            inValue.Body.filmID = filmID;
            WebApp.DataManager.FilmDetayGetirResponse retVal = ((WebApp.DataManager.DataManagerSoap)(this)).FilmDetayGetir(inValue);
            return retVal.Body.FilmDetayGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApp.DataManager.FilmDetayGetirResponse> WebApp.DataManager.DataManagerSoap.FilmDetayGetirAsync(WebApp.DataManager.FilmDetayGetirRequest request) {
            return base.Channel.FilmDetayGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApp.DataManager.FilmDetayGetirResponse> FilmDetayGetirAsync(int filmID) {
            WebApp.DataManager.FilmDetayGetirRequest inValue = new WebApp.DataManager.FilmDetayGetirRequest();
            inValue.Body = new WebApp.DataManager.FilmDetayGetirRequestBody();
            inValue.Body.filmID = filmID;
            return ((WebApp.DataManager.DataManagerSoap)(this)).FilmDetayGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.DataManager.FilmListeleResponse WebApp.DataManager.DataManagerSoap.FilmListele(WebApp.DataManager.FilmListeleRequest request) {
            return base.Channel.FilmListele(request);
        }
        
        public List<WebApp.DataManager.Film> FilmListele() {
            WebApp.DataManager.FilmListeleRequest inValue = new WebApp.DataManager.FilmListeleRequest();
            inValue.Body = new WebApp.DataManager.FilmListeleRequestBody();
            WebApp.DataManager.FilmListeleResponse retVal = ((WebApp.DataManager.DataManagerSoap)(this)).FilmListele(inValue);
            return retVal.Body.FilmListeleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApp.DataManager.FilmListeleResponse> WebApp.DataManager.DataManagerSoap.FilmListeleAsync(WebApp.DataManager.FilmListeleRequest request) {
            return base.Channel.FilmListeleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApp.DataManager.FilmListeleResponse> FilmListeleAsync() {
            WebApp.DataManager.FilmListeleRequest inValue = new WebApp.DataManager.FilmListeleRequest();
            inValue.Body = new WebApp.DataManager.FilmListeleRequestBody();
            return ((WebApp.DataManager.DataManagerSoap)(this)).FilmListeleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.DataManager.FilmSilResponse WebApp.DataManager.DataManagerSoap.FilmSil(WebApp.DataManager.FilmSilRequest request) {
            return base.Channel.FilmSil(request);
        }
        
        public string FilmSil(int Film_Id) {
            WebApp.DataManager.FilmSilRequest inValue = new WebApp.DataManager.FilmSilRequest();
            inValue.Body = new WebApp.DataManager.FilmSilRequestBody();
            inValue.Body.Film_Id = Film_Id;
            WebApp.DataManager.FilmSilResponse retVal = ((WebApp.DataManager.DataManagerSoap)(this)).FilmSil(inValue);
            return retVal.Body.FilmSilResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApp.DataManager.FilmSilResponse> WebApp.DataManager.DataManagerSoap.FilmSilAsync(WebApp.DataManager.FilmSilRequest request) {
            return base.Channel.FilmSilAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApp.DataManager.FilmSilResponse> FilmSilAsync(int Film_Id) {
            WebApp.DataManager.FilmSilRequest inValue = new WebApp.DataManager.FilmSilRequest();
            inValue.Body = new WebApp.DataManager.FilmSilRequestBody();
            inValue.Body.Film_Id = Film_Id;
            return ((WebApp.DataManager.DataManagerSoap)(this)).FilmSilAsync(inValue);
        }
    }
}
